---
# Purpose:
# Phase 1 – Promote Windows Server to Active Directory Domain Controller
# Cyberpunk lab environment

- name: Phase 1 - Promote Domain Controller
  hosts: ADserver
  gather_facts: yes
  vars:
    # Overriding transport to credssp for this specific sensitive play
    ansible_winrm_transport: credssp
    domain_name: cyberpunk.local
    safe_mode_password: "CyberrangeSafeMode123!"

  tasks:
    - name: Install AD-Domain-Services role
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promote server to Domain Controller
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        install_dns: yes
        state: domain_controller
      register: promotion_status

    - name: Reboot after promotion
      win_reboot:
        msg: "Rebooting to finalize Domain Controller promotion"
        pre_reboot_delay: 15
      when: promotion_status.reboot_required