---
# Phase 1: Promote Domain Controller
# This playbook turns a fresh Windows Server into a Domain Controller
# Run with: ansible-playbook -i inventory.ini deploy_ad_p1.yml
# Uses direct PowerShell commands for compatibility

- name: Phase 1 - Promote Domain Controller
  hosts: ADserver
  gather_facts: false
  vars_files:
    - vars/ad/ad.yml
    - vars/ad/local_admin.yml

  tasks:
    - name: Install AD Domain Services feature
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true
      register: ad_install

    - name: Display AD DS installation status
      ansible.builtin.debug:
        msg: "AD DS installed: {{ ad_install.changed }}"

    - name: Check if domain already exists
      ansible.windows.win_shell: |
        try {
            Get-ADDomain -ErrorAction Stop
            Write-Output "EXISTS"
        } catch {
            Write-Output "NOT_EXISTS"
        }
      register: domain_check
      failed_when: false
      changed_when: false

    - name: Promote server to Domain Controller
      ansible.windows.win_shell: |
        $SecurePassword = ConvertTo-SecureString "{{ dsrm_password }}" -AsPlainText -Force
        Install-ADDSForest `
          -DomainName "{{ domain_name }}" `
          -DomainNetbiosName "{{ netbios_name }}" `
          -SafeModeAdministratorPassword $SecurePassword `
          -InstallDns:$true `
          -CreateDnsDelegation:$false `
          -DatabasePath "C:\Windows\NTDS" `
          -SysvolPath "C:\Windows\SYSVOL" `
          -LogPath "C:\Windows\NTDS" `
          -NoRebootOnCompletion:$false `
          -Force:$true
      register: domain_promotion
      when: domain_check.stdout is search("NOT_EXISTS")
      async: 1800
      poll: 0

    - name: Wait for domain promotion to complete (server will reboot)
      ansible.builtin.pause:
        seconds: 120
      when: domain_check.stdout is search("NOT_EXISTS")

    - name: Wait for server to come back online
      wait_for_connection:
        timeout: 900
        delay: 60
      when: domain_check.stdout is search("NOT_EXISTS")

    - name: Wait for AD Web Services to be ready
      ansible.windows.win_shell: |
        $timeout = 300
        $timer = [Diagnostics.Stopwatch]::StartNew()
        while ($timer.Elapsed.TotalSeconds -lt $timeout) {
            try {
                Get-ADDomain -ErrorAction Stop | Out-Null
                Write-Output "READY"
                exit 0
            } catch {
                Start-Sleep -Seconds 10
            }
        }
        Write-Output "TIMEOUT"
        exit 1
      register: ad_ready
      retries: 3
      delay: 30
      until: ad_ready.stdout is search("READY")

    - name: Verify domain controller promotion
      ansible.windows.win_shell: |
        Get-ADDomainController -Identity $env:COMPUTERNAME | Select-Object Name, Domain, IsGlobalCatalog, OperatingSystem
      register: dc_status

    - name: Display domain controller status
      ansible.builtin.debug:
        var: dc_status.stdout_lines

    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "========================================="
          - "Domain Controller Promotion Complete"
          - "========================================="
          - "Domain: {{ domain_name }}"
          - "NetBIOS: {{ netbios_name }}"
          - "Status: Domain controller is ready"
          - "Next: Run Phase 2 to configure AD objects"
          - "========================================="