---
# Purpose:
# Phase 1 – Promote Windows Server to Active Directory Domain Controller
# Cyberpunk lab environment

- name: Phase 1 - Promote Domain Controller
  hosts: ADserver
  gather_facts: false

  vars_files:
    - var/ad/ad.yml
    - var/ad/domain_admin.yml

  tasks:
    - name: Install AD Domain Services
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true

    - name: Check if domain already exists
      ansible.windows.win_shell: |
        try {
          Get-ADDomain -ErrorAction Stop | Out-Null
          Write-Output "EXISTS"
        } catch {
          Write-Output "NOT_EXISTS"
        }
      register: domain_check
      failed_when: false
      changed_when: false

    - name: Promote server to Domain Controller
      ansible.windows.win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        safe_mode_password: "{{ dsrm_password }}"
        state: domain
      when: domain_check.stdout is search("NOT_EXISTS")

    - name: Wait for server reboot after promotion
      wait_for_connection:
        timeout: 900
        delay: 60
      when: domain_check.stdout is search("NOT_EXISTS")

    - name: Verify Domain Controller promotion
      ansible.windows.win_shell: |
        Get-ADDomainController -Identity $env:COMPUTERNAME |
        Select-Object Name, Domain
      register: dc_status

    - name: Display Domain Controller status
      ansible.builtin.debug:
        var: dc_status.stdout_lines
