---
- name: Phase 2 - Configure Active Directory
  hosts: ADserver
  gather_facts: false
  vars_files:
    - vars/ad/ad.yml

  tasks:
    - name: Wait for domain controller services
      wait_for_connection:
        timeout: 600
        delay: 30

    - name: Verify domain services are running
      ansible.windows.win_shell: |
        $services = @('NTDS', 'DNS', 'Netlogon')
        foreach ($svc in $services) {
            $status = Get-Service -Name $svc -ErrorAction SilentlyContinue
            "$svc : $($status.Status)"
        }
      register: service_check
      retries: 5
      delay: 30
      until: service_check.stdout is search("Running")

    - name: Create Organizational Units
      community.windows.win_domain_ou:
        name: "{{ item.name }}"
        path: "{{ domain_dn }}"
        state: present
        protected: true
      loop: "{{ ous }}"

    - name: Create security groups
      community.windows.win_domain_group:
        name: "{{ item.name }}"
        scope: global
        category: security
        path: "OU={{ item.ou }},{{ domain_dn }}"
        description: "{{ item.desc }}"
        state: present
      loop: "{{ groups }}"

    - name: Create Active Directory users
      community.windows.win_domain_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        path: "OU=Users,{{ domain_dn }}"
        description: "{{ item.description }}"
        password_never_expires: false
        user_cannot_change_password: false
        update_password: on_create
      loop: "{{ ad_users }}"

    - name: Add users to security groups
      community.windows.win_domain_group_membership:
        name: "{{ item.group }}"
        members:
          - "{{ item.name }}"
        state: present
      loop: "{{ ad_users }}"

    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "Active Directory Configuration Complete"
          - "Domain: {{ domain_name }}"
          - "OUs: {{ ous | length }}"
          - "Groups: {{ groups | length }}"
          - "Users: {{ ad_users | length }}"