---
# Phase 2: Configure Active Directory
# This playbook configures Active Directory objects after DC promotion
# Run with: ansible-playbook -i inventory.ini deploy_ad_p2.yml -e @vars/ad/domain_admin.yml

- name: Phase 2 - Configure Active Directory
  hosts: ADserver
  gather_facts: false
  vars_files:
    - vars/ad/ad.yml

  tasks:
    - name: Wait for domain controller services to be ready
      ansible.windows.win_wait_for_connection:
        timeout: 600
        delay: 30

    - name: Verify domain services are running
      ansible.windows.win_shell: |
        $services = @('NTDS', 'DNS', 'Netlogon')
        foreach ($svc in $services) {
            $status = Get-Service -Name $svc -ErrorAction SilentlyContinue
            "$svc : $($status.Status)"
        }
      register: service_check
      retries: 5
      delay: 30
      until: service_check.stdout is search("Running")

    - name: Display service status
      ansible.builtin.debug:
        var: service_check.stdout_lines

    - name: Create Organizational Units
      community.windows.win_domain_ou:
        name: "{{ item.name }}"
        path: "{{ domain_dn }}"
        state: present
        protected: true
      loop: "{{ ous }}"
      register: ou_creation

    - name: Create security groups
      community.windows.win_domain_group:
        name: "{{ item.name }}"
        scope: global
        category: security
        path: "OU={{ item.ou }},{{ domain_dn }}"
        description: "{{ item.desc }}"
        state: present
      loop: "{{ groups }}"
      register: group_creation

    - name: Create Active Directory users
      community.windows.win_domain_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        path: "OU=Users,{{ domain_dn }}"
        description: "{{ item.description }}"
        password_never_expires: false
        user_cannot_change_password: false
        update_password: on_create
        attributes:
          mail: "{{ item.name }}@{{ domain_name }}"
      loop: "{{ ad_users }}"
      register: user_creation

    - name: Add users to security groups
      community.windows.win_domain_group_membership:
        name: "{{ item.group }}"
        members:
          - "{{ item.name }}"
        state: present
      loop: "{{ ad_users }}"
      register: group_membership

    - name: Generate summary report
      ansible.builtin.set_fact:
        deployment_summary:
          domain: "{{ domain_name }}"
          ous_created: "{{ ous | length }}"
          groups_created: "{{ groups | length }}"
          users_created: "{{ ad_users | length }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display deployment summary
      ansible.builtin.debug:
        msg:
          - "========================================="
          - "Active Directory Configuration Complete"
          - "========================================="
          - "Domain: {{ deployment_summary.domain }}"
          - "OUs Created: {{ deployment_summary.ous_created }}"
          - "Groups Created: {{ deployment_summary.groups_created }}"
          - "Users Created: {{ deployment_summary.users_created }}"
          - "Timestamp: {{ deployment_summary.timestamp }}"
          - "========================================="
