
- name: Phase 3 - Deploy Windows 11 Client
  hosts: win11client
  gather_facts: false
  vars_files:
    - vars/win11.yml

  tasks:
    - name: Set Hostname
      win_hostname:
        name: "{{ computer_name }}"
      register: res_hostname

    - name: Reboot if hostname changed
      win_reboot:
      when: res_hostname.reboot_required

    - name: Join Cyberpunk Domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_join

    - name: Final Reboot for Domain Connectivity
      win_reboot:
      when: domain_join.reboot_required